const words = [

    { "arabic": "مُعَلِّمُونَ", "translation": "учителя", "lesson": 15 },
    { "arabic": "كَرَاسِيٌّ", "translation": "стулья", "lesson": 15 },
    { "arabic": "يَبِيعُ", "translation": "продажа", "lesson": 15 },
    { "arabic": "الْآنَ", "translation": "сейчас", "lesson": 15 },
    { "arabic": "فَقَطْ", "translation": "только", "lesson": 15 },
    { "arabic": "الْمِصْبَاحُ", "translation": "светильник, лампа", "lesson": 15 },
    { "arabic": "رُؤْيَةٌ", "translation": "видение", "lesson": 15 },
    { "arabic": "إِشْتِرَاءٌ", "translation": "покупка", "lesson": 15 },
    { "arabic": "ثُمَّ", "translation": "потом, затем", "lesson": 15 },
    { "arabic": "ذَهَبُوا", "translation": "они отправились, ушли (м.р.)", "lesson": 15 },
    { "arabic": "قَرَأْتُمْ", "translation": "вы прочли (м.р.)", "lesson": 15 },
    { "arabic": "كَتَبْنَا", "translation": "мы написали", "lesson": 15 },
    { "arabic": "مَعَ", "translation": "вместе", "lesson": 15 },
    { "arabic": "صَاحِبٌ", "translation": "хозяин, друг", "lesson": 15 },


    { "arabic": "طَبَّاخٌ", "translation": "повар", "lesson": 16 },
    { "arabic": "مَطْبَخٌ", "translation": "кухня", "lesson": 16 },
    { "arabic": "إِلْتِفَاتٌ", "translation": "поворачивание", "lesson": 16 },
    { "arabic": "إِحْتِرَامٌ", "translation": "уважение", "lesson": 16 },
    { "arabic": "قَوْلٌ", "translation": "слово", "lesson": 16 },
    { "arabic": "سُوقٌ", "translation": "рынок, базар", "lesson": 16 },
    { "arabic": "سَمَاعٌ", "translation": "слушание", "lesson": 16 },
    { "arabic": "دَائِماً", "translation": "постоянно, всегда", "lesson": 16 },
    { "arabic": "طَبْخٌ", "translation": "варить, готовить пищу", "lesson": 16 },
    { "arabic": "خَادِمٌ", "translation": "слуга", "lesson": 16 },
    { "arabic": "خَادِمَةٌ", "translation": "служанка", "lesson": 16 },
    { "arabic": "يَمِينٌ", "translation": "правый", "lesson": 16 },
    { "arabic": "شِمَالٌ", "translation": "левый", "lesson": 16 },
    { "arabic": "مَخَابِرُ", "translation": "лаборатории", "lesson": 16 },
    { "arabic": "لَا تَلْعَبْ", "translation": "(ты) не играй", "lesson": 16 },
    { "arabic": "لَا تَلْعَبُوا", "translation": "(вы) не играйте (мн. ч. м.р.)", "lesson": 16 },


    { "arabic": "فَأْسٌ", "translation": "топор", "lesson": 17 },
    { "arabic": "مِنْشَارٌ", "translation": "пила", "lesson": 17 },
    { "arabic": "مِكْنَسَةٌ", "translation": "веник, метла", "lesson": 17 },
    { "arabic": "مِطْرَقَةٌ", "translation": "молоток", "lesson": 17 },
    { "arabic": "مُجْتَهِدٌ", "translation": "прилежный", "lesson": 17 },
    { "arabic": "كَسْلَانُ", "translation": "ленивый", "lesson": 17 },
    { "arabic": "كَبِيرٌ", "translation": "большой", "lesson": 17 },
    { "arabic": "صَغِيرٌ", "translation": "маленький", "lesson": 17 },
    { "arabic": "طَوِيلٌ", "translation": "высокий (длинный)", "lesson": 17 },
    { "arabic": "قَصِيرٌ", "translation": "низкий (короткий)", "lesson": 17 },
    { "arabic": "جَدِيدٌ", "translation": "новый", "lesson": 17 },
    { "arabic": "قَدِيمٌ", "translation": "старый", "lesson": 17 },
    { "arabic": "حَادٌّ", "translation": "острый", "lesson": 17 },
    { "arabic": "كَهَامٌ", "translation": "тупой", "lesson": 17 },
    { "arabic": "كَنَسَ", "translation": "мести, подметать", "lesson": 17 },


    { "arabic": "قُفْلٌ", "translation": "замок", "lesson": 18 },
    { "arabic": "صُنْدُوقٌ", "translation": "сундук", "lesson": 18 },
    { "arabic": "مِخْرَزٌ", "translation": "шило", "lesson": 18 },
    { "arabic": "مِفْتَاحٌ", "translation": "ключ", "lesson": 18 },
    { "arabic": "مَفَاتِيحُ", "translation": "ключи", "lesson": 18 },
    { "arabic": "صَنَادِيقُ", "translation": "сундуки", "lesson": 18 },
    { "arabic": "وَاسِعٌ", "translation": "широкий", "lesson": 18 },
    { "arabic": "ضَيِّقٌ", "translation": "узкий", "lesson": 18 },
    { "arabic": "وَضِيعٌ", "translation": "униженный", "lesson": 18 },
    { "arabic": "رَفِيعٌ", "translation": "возвышенный", "lesson": 18 },
    { "arabic": "جَمِيلٌ", "translation": "красивый", "lesson": 18 },
    { "arabic": "قَبِيحٌ", "translation": "некрасивый", "lesson": 18 },
    { "arabic": "مُؤَدَّبٌ", "translation": "воспитанный", "lesson": 18 },
    { "arabic": "غَيْرُ مُؤَدَّبٍ", "translation": "невоспитанный", "lesson": 18 },
    { "arabic": "مُطِيعٌ", "translation": "послушный", "lesson": 18 },
    { "arabic": "عَاصٍ", "translation": "грешный", "lesson": 18 },
    { "arabic": "خَشَبٌ", "translation": "древесина", "lesson": 18 },
    { "arabic": "نَشَرَ", "translation": "пилить", "lesson": 18 },
    { "arabic": "أَقْفَلَ", "translation": "закрывать на замок", "lesson": 18 },
    { "arabic": "فِيَّ", "translation": "меня", "lesson": 18 },
    { "arabic": "كَ", "translation": "тебя", "lesson": 18 },
    { "arabic": "هُ", "translation": "его", "lesson": 18 },


    { "arabic": "مِظَلَّةٌ", "translation": "зонтик", "lesson": 19 },
    { "arabic": "سُلَّمٌ مِعْرَاجٌ", "translation": "лестница", "lesson": 19 },
    { "arabic": "شَارِعٌ", "translation": "улица", "lesson": 19 },
    { "arabic": "مُرُورٌ", "translation": "проходить", "lesson": 19 },
    { "arabic": "مُقْفَلٌ", "translation": "закрытый", "lesson": 19 },
    { "arabic": "مَفْتُوحٌ", "translation": "открытый", "lesson": 19 },
    { "arabic": "مُتَأَخِّرًا", "translation": "поздно", "lesson": 19 },
    { "arabic": "بَاكِرًا", "translation": "рано", "lesson": 19 },
    { "arabic": "مَحْبُوبٌ", "translation": "любимый", "lesson": 19 },
    { "arabic": "مَمْقُوتٌ", "translation": "ненавистный", "lesson": 19 },
    { "arabic": "جَيِّدًا", "translation": "хорошо, отлично", "lesson": 19 },
    { "arabic": "سُقُوطٌ", "translation": "падать, падение", "lesson": 19 },
    { "arabic": "اللَّيْلَةَ", "translation": "сегодня ночью", "lesson": 19 },
    { "arabic": "الْيَوْمَ", "translation": "сегодня днем", "lesson": 19 },


{ "arabic": "بِكُلِّ سُرُورٍ", "translation": "с большим удовольствием", "lesson": 20 },
{ "arabic": "بِكُلِّ إِرْتِيَاحٍ", "translation": "с большим удовольствием", "lesson": 20 },
{ "arabic": "لِيَكْتُبَ", "translation": "чтобы написать", "lesson": 20 },
{ "arabic": "لِيَقْرَأَ", "translation": "чтобы прочитать", "lesson": 20 },
{ "arabic": "لِـ", "translation": "для, чтобы", "lesson": 20 },
{ "arabic": "لَذِيذٌ", "translation": "вкусный", "lesson": 20 },
{ "arabic": "مُرٌّ", "translation": "горький", "lesson": 20 },
{ "arabic": "رِطْلٌ", "translation": "мера веса, равная 144 дирхама", "lesson": 20 },
{ "arabic": "جِدًّا", "translation": "очень", "lesson": 20 },
{ "arabic": "عِنَبٌ", "translation": "виноград", "lesson": 20 },
{ "arabic": "بُرْتُقَالٌ", "translation": "апельсины", "lesson": 20 },
{ "arabic": "تُفَّاحٌ", "translation": "яблоки", "lesson": 20 },
{ "arabic": "لَيْمُونٌ", "translation": "лимоны", "lesson": 20 },
{ "arabic": "بِطِّيخٌ", "translation": "арбуз", "lesson": 20 },
{ "arabic": "شَمَّامٌ", "translation": "дыня", "lesson": 20 },


{ "arabic": "وَاحِدٌ", "translation": "один", "lesson": 21 },
{ "arabic": "إِثْنَانِ", "translation": "два", "lesson": 21 },
{ "arabic": "ثَلَاثَةٌ", "translation": "три", "lesson": 21 },
{ "arabic": "أَرْبَعَةٌ", "translation": "четыре", "lesson": 21 },
{ "arabic": "خَمْسَةٌ", "translation": "пять", "lesson": 21 },
{ "arabic": "سِتَّةٌ", "translation": "шесть", "lesson": 21 },
{ "arabic": "سَبْعَةٌ", "translation": "семь", "lesson": 21 },
{ "arabic": "ثَمَانِيَةٌ", "translation": "восемь", "lesson": 21 },
{ "arabic": "تِسْعَةٌ", "translation": "девять", "lesson": 21 },
{ "arabic": "عَشَرَةٌ", "translation": "десять", "lesson": 21 },
{ "arabic": "مِلِيمٌ", "translation": "меллим", "lesson": 21 },
{ "arabic": "رُوبِلٌ", "translation": "рубль", "lesson": 21 },
{ "arabic": "قِرْشٌ", "translation": "пиастр", "lesson": 21 },
{ "arabic": "جُنَيْهٌ", "translation": "гинея, фунт", "lesson": 21 },
{ "arabic": "قِيمَةٌ", "translation": "цена", "lesson": 21 },
{ "arabic": "كَمْ يَسَاوِي؟", "translation": "сколько стоит?", "lesson": 21 },
{ "arabic": "مِلِيمٌ وَاحِدٌ", "translation": "одна монета", "lesson": 21 },


{ "arabic": "مَكْتَبَةٌ", "translation": "библиотека, книжный", "lesson": 22 },
{ "arabic": "كِتَابٌ", "translation": "книга", "lesson": 22 },
{ "arabic": "إِشْتَغَلَ", "translation": "работать, заняться чем-либо", "lesson": 22 },
{ "arabic": "دَرَّاجَةٌ", "translation": "велосипед", "lesson": 22 },
{ "arabic": "عِشْرُونَ", "translation": "двадцать", "lesson": 22 },
{ "arabic": "ثَلَاثُونَ", "translation": "тридцать", "lesson": 22 },
{ "arabic": "أَرْبَعُونَ", "translation": "сорок", "lesson": 22 },
{ "arabic": "خَمْسُونَ", "translation": "пятьдесят", "lesson": 22 },
{ "arabic": "سِتُّونَ", "translation": "шестьдесят", "lesson": 22 },
{ "arabic": "سَبْعُونَ", "translation": "семьдесят", "lesson": 22 },
{ "arabic": "ثَمَانُونَ", "translation": "восемьдесят", "lesson": 22 },
{ "arabic": "تِسْعُونَ", "translation": "девяносто", "lesson": 22 },


{ "arabic": "سَنَةٌ", "translation": "год", "lesson": 23 },
{ "arabic": "فَصْلٌ", "translation": "время года, сезон", "lesson": 23 },
{ "arabic": "شَهْرٌ", "translation": "месяц", "lesson": 23 },
{ "arabic": "أُسْبُوعٌ", "translation": "неделя", "lesson": 23 },
{ "arabic": "يَوْمٌ", "translation": "день, сутки", "lesson": 23 },
{ "arabic": "نَهَارٌ", "translation": "день, дневное время", "lesson": 23 },
{ "arabic": "لَيْلٌ", "translation": "ночь", "lesson": 23 },
{ "arabic": "ثَانِيَةٌ", "translation": "секунда", "lesson": 23 },
{ "arabic": "دَقِيقَةٌ", "translation": "минута", "lesson": 23 },
{ "arabic": "رَبِيعٌ", "translation": "весна", "lesson": 23 },
{ "arabic": "صَيْفٌ", "translation": "лето", "lesson": 23 },
{ "arabic": "خَرِيفٌ", "translation": "осень", "lesson": 23 },
{ "arabic": "شِتَاءٌ", "translation": "зима", "lesson": 23 },
{ "arabic": "خَمْسَةَ عَشَرَ", "translation": "пятнадцать", "lesson": 23 },
{ "arabic": "ثَلَاثَةٌ وَعِشْرُونَ", "translation": "двадцать три", "lesson": 23 },
{ "arabic": "مِئَةٌ", "translation": "сто", "lesson": 23 },
{ "arabic": "مِئَةٌ وَخَمْسَةَ عَشَرَ", "translation": "сто пятнадцать", "lesson": 23 },
{ "arabic": "أَلْفٌ", "translation": "тысяча", "lesson": 23 },


  { "arabic": "فُرْشَةٌ", "translation": "щётка", "lesson": 24 },
  { "arabic": "إِبْرِيقٌ", "translation": "кувшин", "lesson": 24 },
  { "arabic": "مِنْشَفَةٌ", "translation": "полотенце", "lesson": 24 },
  { "arabic": "يَتَوَضَّأُ", "translation": "совершает омовение", "lesson": 24 },
  { "arabic": "يُصَلِّي", "translation": "совершает намаз", "lesson": 24 },
  { "arabic": "صَابُونٌ", "translation": "мыло", "lesson": 24 },
  { "arabic": "غَسْلٌ", "translation": "мытьё, стирка", "lesson": 24 },
  { "arabic": "تَنْشِيفٌ", "translation": "осушение, вытирание", "lesson": 24 },
  { "arabic": "وَجْهٌ", "translation": "лицо", "lesson": 24 },
  { "arabic": "صَلَاةٌ", "translation": "намаз", "lesson": 24 },
  { "arabic": "فَجْرٌ", "translation": "утренний намаз", "lesson": 24 },
  { "arabic": "ظُهْرٌ", "translation": "обеденный намаз", "lesson": 24 },
  { "arabic": "عَصْرٌ", "translation": "послеполуденный намаз", "lesson": 24 },
  { "arabic": "مَغْرِبٌ", "translation": "вечерний намаз", "lesson": 24 },
  { "arabic": "عِشَاءٌ", "translation": "ночной намаз", "lesson": 24 },
  { "arabic": "طَسْتٌ", "translation": "тазик", "lesson": 24 },
  { "arabic": "عِيدٌ", "translation": "праздник", "lesson": 24 },

 { arabic: "إِنْسَانٌ", translation: "человек", lesson: 25 },
  { arabic: "نَاسٌ", translation: "люди", lesson: 25 },
  { arabic: "النَّبِيُّ", translation: "пророк", lesson: 25 },
  { arabic: "أُذُنٌ", translation: "ухо", lesson: 25 },
  { arabic: "رَأْسٌ", translation: "голова", lesson: 25 },
  { arabic: "شَعْرٌ", translation: "волосы", lesson: 25 },
  { arabic: "جَبْهَةٌ", translation: "лоб", lesson: 25 },
  { arabic: "عَيْنٌ", translation: "глаз", lesson: 25 },
  { arabic: "حَاجِبٌ", translation: "бровь", lesson: 25 },
  { arabic: "شَفَةٌ", translation: "губа", lesson: 25 },
  { arabic: "أَنْفٌ", translation: "нос", lesson: 25 },
  { arabic: "فَمٌ", translation: "рот", lesson: 25 },
  { arabic: "لِسَانٌ", translation: "язык", lesson: 25 },
  { arabic: "يَدٌ", translation: "рука", lesson: 25 },
  { arabic: "إِصْبَعٌ", translation: "палец", lesson: 25 },
  { arabic: "أَمْسَكَ", translation: "держать", lesson: 25 },
  { arabic: "كَذِبٌ", translation: "ложь", lesson: 25 },
  { arabic: "بَعْضٌ", translation: "часть", lesson: 25 },
  { arabic: "كُلٌّ", translation: "все, полностью", lesson: 25 },
  { arabic: "لِي", translation: "мне, для меня", lesson: 25 },
  { arabic: "لَكَ", translation: "тебе, для тебя", lesson: 25 },


  { arabic: "جَفْنٌ", translation: "веко", lesson: 26 },
  { arabic: "هُدْبٌ", translation: "ресницы", lesson: 26 },
  { arabic: "كَفٌّ", translation: "ладонь", lesson: 26 },
  { arabic: "عُنُقٌ", translation: "шея", lesson: 26 },
  { arabic: "أَمَلَةٌ", translation: "кончик пальца", lesson: 26 },
  { arabic: "ظُفْرٌ", translation: "ноготь", lesson: 26 },
  { arabic: "شَارِبٌ", translation: "усы", lesson: 26 },
  { arabic: "أَبْيَضُ", translation: "белый", lesson: 26 },
  { arabic: "أَسْوَدُ", translation: "черный", lesson: 26 },
  { arabic: "لَا يَكْذِبُ", translation: "не обманывает", lesson: 26 },
  { arabic: "لَا", translation: "нет", lesson: 26 },
  { arabic: "أَبَدًا", translation: "всегда", lesson: 26 },
  { arabic: "تُحَرِّكُ", translation: "шевелить", lesson: 26 },
  { arabic: "فَخْذٌ", translation: "ляжка", lesson: 26 },



  { "arabic": "لِحْيَةٌ", "translation": "борода", "lesson": 27 },
  { "arabic": "يَدٌ يُمْنَى", "translation": "правая рука", "lesson": 27 },
  { "arabic": "يَدٌ يُسْرَى", "translation": "левая рука", "lesson": 27 },
  { "arabic": "شَفَةٌ سُفْلَى", "translation": "нижняя губа", "lesson": 27 },
  { "arabic": "شَفَةٌ عُلْيَا", "translation": "верхняя губа", "lesson": 27 },
  { "arabic": "سِنٌّ", "translation": "зуб", "lesson": 27 },
  { "arabic": "رُكْبَةٌ", "translation": "колено", "lesson": 27 },
  { "arabic": "مِرْفَقٌ", "translation": "локоть", "lesson": 27 },
  { "arabic": "كَعْبٌ", "translation": "пятка", "lesson": 27 },
  { "arabic": "رَاحَةٌ", "translation": "ладонь", "lesson": 27 },
  { "arabic": "رِجْلٌ", "translation": "нога", "lesson": 27 },
  { "arabic": "قَدَمٌ", "translation": "стопа", "lesson": 27 },
  { "arabic": "مَا جَاءَ أَحَدٌ", "translation": "ни кто не пришёл", "lesson": 27 },
  { "arabic": "مَا فَهِمَ أَحَدٌ", "translation": "ни кто не понял", "lesson": 27 },
  { "arabic": "مَا قَرَأَ أَحَدٌ", "translation": "ни кто не прочел", "lesson": 27 },
  { "arabic": "كُلُّ أَحَدٍ", "translation": "каждый", "lesson": 27 },


 { "arabic": "صَبَاحًا", "translation": "утром", "lesson": 28 },
  { "arabic": "غَدًا", "translation": "завтра", "lesson": 28 },
  { "arabic": "مَسَاءً", "translation": "вечером", "lesson": 28 },
  { "arabic": "أَمْسِ", "translation": "вчера", "lesson": 28 },
  { "arabic": "قِطَارٌ", "translation": "поезд", "lesson": 28 },
  { "arabic": "كَيْفَ حَالُكَ؟", "translation": "как дела?", "lesson": 28 },
  { "arabic": "كَيْفَ حَفِظَكَ اللهُ", "translation": "да хранит тебя Аллах", "lesson": 28 },
  { "arabic": "عِنْدِي", "translation": "у меня", "lesson": 28 },
  { "arabic": "عِنْدَكَ", "translation": "у тебя", "lesson": 28 },
  { "arabic": "عِنْدَهُ", "translation": "у него", "lesson": 28 },
  { "arabic": "سَيِّدِي", "translation": "мой господин", "lesson": 28 },
  { "arabic": "مَحَطَّةٌ", "translation": "вокзал", "lesson": 28 },
  { "arabic": "تَوَجُّهٌ", "translation": "направление", "lesson": 28 },
  { "arabic": "سِكَّةٌ حَدِيدِيَّةٌ", "translation": "железная дорога", "lesson": 28 },



  { "arabic": "جَائِعٌ", "translation": "голодный", "lesson": 29 },
  { "arabic": "عَطْشَانُ", "translation": "жаждущий", "lesson": 29 },
  { "arabic": "كَرِيمٌ", "translation": "щедрый", "lesson": 29 },
  { "arabic": "بَخِيلٌ", "translation": "скупой", "lesson": 29 },
  { "arabic": "عَاصِمَةٌ", "translation": "столица", "lesson": 29 },
  { "arabic": "رُجُوعٌ", "translation": "возвращаться", "lesson": 29 },
  { "arabic": "قَرْيَةٌ", "translation": "село", "lesson": 29 },
  { "arabic": "غَالٍ", "translation": "дорогой", "lesson": 29 },
  { "arabic": "رَخِيصٌ", "translation": "дешёвый", "lesson": 29 },
  { "arabic": "إِحْسَانٌ", "translation": "давать милостыню, добро", "lesson": 29 },
  { "arabic": "شُكْرٌ", "translation": "благодарность", "lesson": 29 },
  { "arabic": "بَقَاءٌ", "translation": "оставаться", "lesson": 29 },
  { "arabic": "أَبَوَانِ", "translation": "родители", "lesson": 29 },
  { "arabic": "أَقَارِبُ", "translation": "близкие родственники", "lesson": 29 },




  { "arabic": "مُعَلِّمٌ", "translation": "учитель", "lesson": 30 },
  { "arabic": "مُعَلِّمَةٌ", "translation": "учительница", "lesson": 30 },
  { "arabic": "تِلْمِيذٌ", "translation": "ученик", "lesson": 30 },
  { "arabic": "تِلْمِيذَةٌ", "translation": "ученица", "lesson": 30 },
  { "arabic": "تَلَامِيذُ", "translation": "ученики", "lesson": 30 },
  { "arabic": "تِلْمِيذَاتٌ", "translation": "ученицы", "lesson": 30 },
  { "arabic": "رَجُلٌ", "translation": "мужчина", "lesson": 30 },
  { "arabic": "رِجَالٌ", "translation": "мужчины", "lesson": 30 },
  { "arabic": "اِمْرَأَةٌ", "translation": "женщина", "lesson": 30 },
  { "arabic": "نِسَاءٌ", "translation": "женщины", "lesson": 30 },
  { "arabic": "هَذِهِ", "translation": "эта", "lesson": 30 },
  { "arabic": "تِلْكَ", "translation": "та", "lesson": 30 },
  { "arabic": "كَبِيرَةٌ", "translation": "большая, взрослая", "lesson": 30 },
  { "arabic": "مُؤَدَّبَةٌ", "translation": "воспитанная", "lesson": 30 },


  { "arabic": "عَالِمٌ", "translation": "учёный", "lesson": 31 },
  { "arabic": "عُلَمَاءُ", "translation": "учёные", "lesson": 31 },
  { "arabic": "جَاهِلٌ", "translation": "невежда", "lesson": 31 },
  { "arabic": "جُهَلَاءُ", "translation": "невежды", "lesson": 31 },
  { "arabic": "فَاضِلٌ", "translation": "достойный, превосходный", "lesson": 31 },
  { "arabic": "فُضَلَاءُ", "translation": "достойные, превосходные", "lesson": 31 },
  { "arabic": "تَكْتُبُ", "translation": "(ты) пишешь", "lesson": 31 },
  { "arabic": "تَقْرَأُ", "translation": "(ты) читаешь", "lesson": 31 },
  { "arabic": "هِيَ", "translation": "она", "lesson": 31 },
  { "arabic": "كُتَّابٌ", "translation": "начальная школа", "lesson": 31 },



  { "arabic": "مِشْطٌ", "translation": "расчёска", "lesson": 32 },
  { "arabic": "تَرَابِيزَةٌ", "translation": "стол (таблица)", "lesson": 32 },
  { "arabic": "مِرْآةٌ", "translation": "зеркало", "lesson": 32 },
  { "arabic": "هَا", "translation": "ей", "lesson": 32 },
  { "arabic": "كِ", "translation": "тебе (ж.р.)", "lesson": 32 },
  { "arabic": "تَعَالِي", "translation": "иди (ж.р.)", "lesson": 32 },
  { "arabic": "اُكْتُبِي يَا عَائِشَةُ", "translation": "напиши, о Аиша", "lesson": 32 },
  { "arabic": "تُمَشِّطُ", "translation": "расчёсываться", "lesson": 32 }, 


  { "arabic": "تَنْظِيفٌ", "translation": "протирание, чистка", "lesson": 33 },
  { "arabic": "نَظِيفٌ", "translation": "чистый", "lesson": 33 },
  { "arabic": "يَكُونُ", "translation": "будет", "lesson": 33 },
  { "arabic": "تَلْوِيثٌ", "translation": "пачкать, загрязнять", "lesson": 33 },
  { "arabic": "وَسِخٌ", "translation": "быть грязным", "lesson": 33 },
  { "arabic": "مَسْحٌ", "translation": "протирать, чистить", "lesson": 33 },
  { "arabic": "أَمَّا", "translation": "что касается", "lesson": 33 },
  { "arabic": "لِبَاسٌ", "translation": "одежда", "lesson": 33 },
  { "arabic": "هَاتِي", "translation": "дай (ж.р.)", "lesson": 33 },
  { "arabic": "كُنْ", "translation": "будь", "lesson": 33 },
  { "arabic": "مِنْدِيلٌ", "translation": "носовой платок", "lesson": 33 },
  { "arabic": "فِرَاشٌ", "translation": "постель", "lesson": 33 },
  { "arabic": "تَكْتُبِينَ", "translation": "(ты) пишешь (ед.ч., ж.р.)", "lesson": 33 },



  { "arabic": "شَجَرٌ", "translation": "дерево", "lesson": 34 },
  { "arabic": "حَجَرٌ", "translation": "камень", "lesson": 34 },
  { "arabic": "لَبِنٌ", "translation": "кирпичи, саман (молоко)", "lesson": 34 },
  { "arabic": "نَبْتٌ", "translation": "растение, трава", "lesson": 34 },
  { "arabic": "تَنْوِيمٌ", "translation": "усыпление, укладывание спать", "lesson": 34 },
  { "arabic": "إِحْضَارٌ", "translation": "принести", "lesson": 34 },
  { "arabic": "حَاضِنَةٌ", "translation": "кормилица", "lesson": 34 },
  { "arabic": "إِعْطَاءٌ", "translation": "отдавать, раздача", "lesson": 34 },
  { "arabic": "لَعِبَتْ", "translation": "она играла", "lesson": 34 },
  { "arabic": "لَعِبْتَ", "translation": "ты играл(а)", "lesson": 34 },
  { "arabic": "مَا كَتَبْتُ بَعْدَ", "translation": "я не писал после", "lesson": 34 },
  { "arabic": "وَلِيدٌ", "translation": "ребёнок", "lesson": 34 },
  { "arabic": "مَهْدٌ", "translation": "колыбель", "lesson": 34 },
  { "arabic": "قِمَاطٌ", "translation": "пелёнка", "lesson": 34 },
  { "arabic": "قِمَاطٌ", "translation": "пеленать", "lesson": 34 },






  { "arabic": "قِدْرٌ", "translation": "котёл", "lesson": 35 },
  { "arabic": "بَرْمِيلٌ", "translation": "бочка", "lesson": 35 },
  { "arabic": "كَمَّاشَةٌ", "translation": "щипцы, клещи", "lesson": 35 },
  { "arabic": "مِبْرَدٌ", "translation": "напильник", "lesson": 35 },
  { "arabic": "مِجْرَفَةٌ", "translation": "лопата, грабли", "lesson": 35 },
  { "arabic": "لِجَامٌ", "translation": "уздечка", "lesson": 35 },
  { "arabic": "سَرْجٌ", "translation": "седло", "lesson": 35 },
  { "arabic": "إِسْرَاجٌ", "translation": "седлать", "lesson": 35 },
  { "arabic": "إِلْجَامٌ", "translation": "обуздывать", "lesson": 35 },
  { "arabic": "حَدِيدٌ", "translation": "железо", "lesson": 35 },
  { "arabic": "نُحَاسٌ", "translation": "медь", "lesson": 35 },
  { "arabic": "قَصْدِيرٌ", "translation": "олово", "lesson": 35 },
  { "arabic": "فُولَاذٌ", "translation": "сталь", "lesson": 35 },
  { "arabic": "مُوسَى", "translation": "лезвие", "lesson": 35 },
  { "arabic": "آلَةٌ", "translation": "инструмент", "lesson": 35 },
  { "arabic": "صَنْعَةٌ", "translation": "ремесло", "lesson": 35 },
  { "arabic": "مَاذَا", "translation": "что", "lesson": 35 },
  { "arabic": "وَغَيْرُ ذَلِكَ", "translation": "и другие", "lesson": 35 }


]